'TUORLO D’UOVO MARINATO','CARLO CRACCO'
'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI'
'CIPOLLA CARAMELLATA','DAVIDE OLDANI'
'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO'