Santo80,'PASTA AL PESTO','MASSIMO BOTTURA',3
Santo80,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Santo80,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',2
Santo80,'PASTA E PATATE','NIKO ROMITO',4
Santo80,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',3
Santo80,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Santo80,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',1
Santo80,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',4
Santo80,'PASTA ALLA MARINARA','ENRICO CEREA',3
Santo80,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',NULL
Santo80,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',NULL
Manzi58,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Manzi58,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Manzi58,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',NULL
Manzi58,'PASTA E PATATE','NIKO ROMITO',NULL
Manzi58,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',NULL
Manzi58,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Manzi58,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Manzi58,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',5
Manzi58,'PASTA ALLA MARINARA','ENRICO CEREA',3
Manzi58,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',4
Manzi58,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',4
Casati96,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Casati96,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Casati96,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',4
Casati96,'PASTA E PATATE','NIKO ROMITO',3
Casati96,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',NULL
Casati96,'TUORLO D’UOVO MARINATO','CARLO CRACCO',5
Casati96,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',1
Casati96,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',3
Casati96,'PASTA ALLA MARINARA','ENRICO CEREA',4
Casati96,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',4
Casati96,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',NULL
Dylan69,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Dylan69,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Dylan69,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',NULL
Dylan69,'PASTA E PATATE','NIKO ROMITO',NULL
Dylan69,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',NULL
Dylan69,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Dylan69,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Dylan69,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',NULL
Dylan69,'PASTA ALLA MARINARA','ENRICO CEREA',NULL
Dylan69,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',NULL
Dylan69,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',NULL
Paga61,'PASTA AL PESTO','MASSIMO BOTTURA',4
Paga61,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Paga61,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',2
Paga61,'PASTA E PATATE','NIKO ROMITO',1
Paga61,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',NULL
Paga61,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Paga61,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Paga61,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',3
Paga61,'PASTA ALLA MARINARA','ENRICO CEREA',4
Paga61,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',3
Paga61,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',4
Jhon59,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Jhon59,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Jhon59,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',NULL
Jhon59,'PASTA E PATATE','NIKO ROMITO',NULL
Jhon59,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',4
Jhon59,'TUORLO D’UOVO MARINATO','CARLO CRACCO',3
Jhon59,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Jhon59,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',1
Jhon59,'PASTA ALLA MARINARA','ENRICO CEREA',NULL
Jhon59,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',NULL
Jhon59,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',3
Dalia81,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Dalia81,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Dalia81,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',NULL
Dalia81,'PASTA E PATATE','NIKO ROMITO',NULL
Dalia81,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',3
Dalia81,'TUORLO D’UOVO MARINATO','CARLO CRACCO',1
Dalia81,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Dalia81,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',3
Dalia81,'PASTA ALLA MARINARA','ENRICO CEREA',5
Dalia81,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',4
Dalia81,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',3
Orazio22,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Orazio22,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Orazio22,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',4
Orazio22,'PASTA E PATATE','NIKO ROMITO',3
Orazio22,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',NULL
Orazio22,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Orazio22,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',1
Orazio22,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',2
Orazio22,'PASTA ALLA MARINARA','ENRICO CEREA',3
Orazio22,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',4
Orazio22,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',3
Brunelli26,'PASTA AL PESTO','MASSIMO BOTTURA',3
Brunelli26,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Brunelli26,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',3
Brunelli26,'PASTA E PATATE','NIKO ROMITO',1
Brunelli26,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',3
Brunelli26,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Brunelli26,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',2
Brunelli26,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',5
Brunelli26,'PASTA ALLA MARINARA','ENRICO CEREA',4
Brunelli26,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',2
Brunelli26,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',3
Girolamo52,'PASTA AL PESTO','MASSIMO BOTTURA',NULL
Girolamo52,'GNOCCHI ALLA SORRENTINA','MASSIMILIANO ALAJMO',5
Girolamo52,'PASTA FREDDA PESTO MOZZARELLA E POMODORINI','ENRICO CRIPPA',4
Girolamo52,'PASTA E PATATE','NIKO ROMITO',4
Girolamo52,'CONCHIGLIONI CON CREMA DI FORMAGGIO','MATTEO BARONETTO',3
Girolamo52,'TUORLO D’UOVO MARINATO','CARLO CRACCO',NULL
Girolamo52,'BIANCO E NERO DI SEPPIA','LUIGI TAGLIENTI',1
Girolamo52,'INSALATA DI RINFORZO','SILVIO SALMOIRAGHI',NULL
Girolamo52,'PASTA ALLA MARINARA','ENRICO CEREA',5
Girolamo52,'CIPOLLA CARAMELLATA','DAVIDE OLDANI',3
Girolamo52,'TRIGLIA DI SCOGLIO E CAVIALE DI MELANZANE CON SALSE AL FRUTTO DELLA PASSIONE','ANTONINO CANNAVACIUOLO',4